# Generated by Django 5.2.7 on 2025-11-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('appr_minutes_todo', models.IntegerField(default=15)),
                ('importance', models.PositiveIntegerField(default=1)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('notify_before_min', models.IntegerField(default=15)),
            ],
        ),
    ]
