# Generated by Django 5.2.7 on 2025-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='appr_minutes_todo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notify_before_min',
        ),
        migrations.AddField(
            model_name='event',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
