# Generated by Django 5.2.7 on 2025-12-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
    ]
